-- 0001_init.sql
-- Initial schema migration for GhostPilot.
-- Generated by Drizzle Kit — do NOT edit manually.

CREATE TABLE IF NOT EXISTS `personas` (
  `id` text PRIMARY KEY NOT NULL,
  `name` text NOT NULL,
  `bio` text NOT NULL DEFAULT '',
  `pillars` text NOT NULL DEFAULT '[]',
  `style_hints` text NOT NULL DEFAULT '',
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `style_fingerprints` (
  `id` text PRIMARY KEY NOT NULL,
  `persona_id` text NOT NULL REFERENCES `personas`(`id`) ON DELETE CASCADE,
  `embedding_json` text NOT NULL DEFAULT '[]',
  `descriptors` text NOT NULL DEFAULT '[]',
  `avg_sentence_length` real NOT NULL DEFAULT 0,
  `tone` text NOT NULL DEFAULT '',
  `computed_at` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `posts` (
  `id` text PRIMARY KEY NOT NULL,
  `persona_id` text NOT NULL REFERENCES `personas`(`id`) ON DELETE CASCADE,
  `status` text NOT NULL DEFAULT 'draft',
  `body` text NOT NULL DEFAULT '',
  `platforms` text NOT NULL DEFAULT '[]',
  `scheduled_at` integer,
  `published_at` integer,
  `attempts` integer NOT NULL DEFAULT 0,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `draft_variants` (
  `id` text PRIMARY KEY NOT NULL,
  `post_id` text NOT NULL REFERENCES `posts`(`id`) ON DELETE CASCADE,
  `platform` text NOT NULL,
  `body` text NOT NULL,
  `char_count` integer NOT NULL DEFAULT 0,
  `style_drift_score` real NOT NULL DEFAULT 0,
  `provider` text NOT NULL,
  `model_id` text NOT NULL,
  `created_at` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `jobs` (
  `id` text PRIMARY KEY NOT NULL,
  `post_id` text NOT NULL REFERENCES `posts`(`id`) ON DELETE CASCADE,
  `variant_id` text NOT NULL REFERENCES `draft_variants`(`id`),
  `platform` text NOT NULL,
  `scheduled_at` integer NOT NULL,
  `status` text NOT NULL DEFAULT 'pending',
  `attempts` integer NOT NULL DEFAULT 0,
  `last_error` text,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `social_connections` (
  `id` text PRIMARY KEY NOT NULL,
  `platform` text NOT NULL,
  `platform_user_id` text NOT NULL,
  `display_name` text NOT NULL DEFAULT '',
  `keychain_key` text NOT NULL,
  `expires_at` integer,
  `scopes` text NOT NULL DEFAULT '[]',
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `llm_usage` (
  `id` text PRIMARY KEY NOT NULL,
  `ts` integer NOT NULL,
  `provider` text NOT NULL,
  `model_id` text NOT NULL,
  `task` text NOT NULL,
  `prompt_tokens` integer NOT NULL DEFAULT 0,
  `completion_tokens` integer NOT NULL DEFAULT 0,
  `estimated_cost_usd` real NOT NULL DEFAULT 0,
  `post_id` text,
  `persona_id` text
);

CREATE TABLE IF NOT EXISTS `intents` (
  `id` text PRIMARY KEY NOT NULL,
  `persona_id` text NOT NULL REFERENCES `personas`(`id`) ON DELETE CASCADE,
  `title` text NOT NULL,
  `description` text NOT NULL DEFAULT '',
  `horizon` text NOT NULL,
  `created_at` integer NOT NULL,
  `updated_at` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `key_results` (
  `id` text PRIMARY KEY NOT NULL,
  `intent_id` text NOT NULL REFERENCES `intents`(`id`) ON DELETE CASCADE,
  `title` text NOT NULL,
  `target` real NOT NULL DEFAULT 0,
  `current` real NOT NULL DEFAULT 0,
  `unit` text NOT NULL DEFAULT '',
  `weekly_quota` text NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS `trend_clusters` (
  `id` text PRIMARY KEY NOT NULL,
  `title` text NOT NULL,
  `summary` text NOT NULL DEFAULT '',
  `relevance_score` real NOT NULL DEFAULT 0,
  `velocity_score` real NOT NULL DEFAULT 0,
  `novelty_score` real NOT NULL DEFAULT 0,
  `composite_score` real NOT NULL DEFAULT 0,
  `detected_at` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `trend_evidence` (
  `id` text PRIMARY KEY NOT NULL,
  `cluster_id` text NOT NULL REFERENCES `trend_clusters`(`id`) ON DELETE CASCADE,
  `source` text NOT NULL,
  `url` text NOT NULL,
  `title` text NOT NULL,
  `score` real NOT NULL DEFAULT 0,
  `fetched_at` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS `context_chunks` (
  `id` text PRIMARY KEY NOT NULL,
  `persona_id` text NOT NULL REFERENCES `personas`(`id`) ON DELETE CASCADE,
  `source_file` text NOT NULL,
  `chunk_index` integer NOT NULL,
  `content` text NOT NULL,
  `embedding_json` text NOT NULL DEFAULT '[]',
  `created_at` integer NOT NULL
);

-- FTS5 virtual table for hybrid BM25 retrieval
CREATE VIRTUAL TABLE IF NOT EXISTS `context_chunks_fts` USING fts5(
  content,
  content='context_chunks',
  content_rowid='rowid'
);

CREATE TABLE IF NOT EXISTS `settings` (
  `key` text PRIMARY KEY NOT NULL,
  `value` text NOT NULL DEFAULT '',
  `updated_at` integer NOT NULL
);
